%YAML:1.0
# # trifo 3058
# 根据calib_PI_3058.json进行的编写


#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 0         
num_of_cam: 2  

imu_topic: "/imu0"
image0_topic: "/cam0/image_raw"
image1_topic: "/cam1/image_raw"
output_path: "/home/kuan/4VINS_test/result/trifo/3058test1/"

cam0_calib: "cam0_KB.yaml"
cam1_calib: "cam1_KB.yaml"
image_width: 640
image_height: 480
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1, 0, 0, -0.059389999999999998,
           0, 1, 0, -0.002,
           0, 0, 1, 0.064909700000000001,
           0, 0, 0, 1]


        # [0.99999928431483143, -0.000705014534815941, -0.00096660453689961833, 0.064430666649054891,
        # 0.00070627715377302464, 0.99999889708451184, 0.0013065229972316994, 0.00082225492951573144,
        # 0.00096568235311406429, -0.001307204752874, 0.9999986793357919, 0.00024929714576983055,
        #    0, 0, 0, 1]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.999999284314831, -7.050145348159410e-04, -9.666045368996183e-04, 0.005040666649055,
            7.062771537730246e-04, 0.999998897084512, 0.001306522997232, -0.001177745070484,
            9.656823531140643e-04, -0.00130720475287371, 0.999998679335792, 0.065158997145770,
            0, 0, 0, 1]


#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)
